---
language: python
services: docker

env:
  global:
    - REPO_NAME: ansible-role-cloud-sql-proxy
    - ROLE_NAME: davidalger.cloud_sql_proxy

  matrix:
    - MOLECULE_DISTRO: centos7
      MOLECULE_DOCKER_COMMAND: /usr/lib/systemd/systemd

install:
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv $REPO_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
